INSERT INTO interests(interest_name) VALUES('Звёздные войны');
INSERT INTO interests(interest_name) VALUES('Чтение');
INSERT INTO interests(interest_name) VALUES('Компьтерные игры');
INSERT INTO interests(interest_name) VALUES('Программирование');
INSERT INTO interests(interest_name) VALUES('Садоводство');
INSERT INTO interests(interest_name) VALUES('Гитара');
INSERT INTO interests(interest_name) VALUES('Барабаны');
INSERT INTO interests(interest_name) VALUES('Фантастика');
INSERT INTO interests(interest_name) VALUES('Фотография');
INSERT INTO interests(interest_name) VALUES('Косметика');
INSERT INTO interests(interest_name) VALUES('Чай');
INSERT INTO interests(interest_name) VALUES('Сладкое');
INSERT INTO interests(interest_name) VALUES('Гарри Поттер');
INSERT INTO interests(interest_name) VALUES('Dota');
INSERT INTO interests(interest_name) VALUES('Minecraft');
INSERT INTO interests(interest_name) VALUES('Fortnite');
INSERT INTO interests(interest_name) VALUES('Overwatch');
INSERT INTO interests(interest_name) VALUES('Игра Престолов');
INSERT INTO interests(interest_name) VALUES('Властелин колец');
INSERT INTO interests(interest_name) VALUES('Ведьмак');
INSERT INTO interests(interest_name) VALUES('Музыка');
INSERT INTO interests(interest_name) VALUES('Манга');
INSERT INTO interests(interest_name) VALUES('Аниме');
INSERT INTO interests(interest_name) VALUES('Лёгкая атлетика');
INSERT INTO interests(interest_name) VALUES('Пауерлифтинг');
